In [1]:
import numpy as np

size = 10
data = np.random.rand(size)
average = np.mean(data)

# Calculating variance using inbuilt function
variance = np.var(data)
print(f"Data: {data}")
print(f"Average: {average}")
print(f"Variance: {variance}")

# Calculate variance manually
manual_variance = sum((value - average) ** 2 for value in data) / size
print(manual_variance)


Data: [0.83677269 0.33872425 0.85281497 0.21460176 0.31566794 0.11730599
 0.26555038 0.15541886 0.67710759 0.15845201]
Average: 0.39324164541056306
Variance: 0.073354072778813
0.07335407277881302


In [2]:
import numpy as np

size = 10
vector_a = np.random.rand(size)
vector_b = np.random.rand(size)
mean_a = np.mean(vector_a)
mean_b = np.mean(vector_b)

# Calculate covariance manually
manual_covariance = sum((vector_a[i] - mean_a) * (vector_b[i] - mean_b) for i in range(size)) / size
print(f"Vector A: {vector_a}")
print(f"Vector B: {vector_b}")
print(f"Mean of Vector A: {mean_a}")
print(f"Mean of Vector B: {mean_b}")
print(f"Covariance: {manual_covariance}")

# Calculate covariance using inbuilt function
cov_matrix = np.cov(vector_b, vector_a, bias=True)
cov_ab = cov_matrix[0, 1]
print(cov_ab)


Vector A: [0.28540843 0.59797264 0.69770303 0.68462958 0.9533165  0.71544879
 0.45290025 0.96477185 0.94683038 0.13459803]
Vector B: [0.79124534 0.02013843 0.49805311 0.13498775 0.39982202 0.59518254
 0.69250565 0.14614742 0.4106975  0.60787526]
Mean of Vector A: 0.6433579471339862
Mean of Vector B: 0.4296654995867205
Covariance: -0.03542129231267922
-0.03542129231267922


In [3]:
import numpy as np

num_samples = 10
vector_one = np.random.rand(num_samples)
vector_two = np.random.rand(num_samples)
correlation_matrix = np.corrcoef(vector_one, vector_two)
correlation_value = correlation_matrix[0, 1]  # Extract the correlation value

print(f"Vector One: {vector_one}")
print(f"Vector Two: {vector_two}")
print(f"Correlation: {correlation_value}")



Vector One: [0.2200016  0.35341296 0.92487698 0.8757381  0.52803078 0.38340173
 0.09748241 0.23870806 0.179257   0.84274616]
Vector Two: [0.24558934 0.18135578 0.89488677 0.76055464 0.83823092 0.27623097
 0.20665567 0.48025619 0.78933393 0.67107647]
Correlation: 0.6463514454639595


In [4]:
import numpy as np

num_features = 4    # Number of features
num_samples = 10    # Number of samples
data_matrix = np.random.rand(num_features, num_samples)
cov_matrix = np.cov(data_matrix, rowvar=True, bias=True)
corr_matrix = np.corrcoef(data_matrix)

print("Data Matrix (features x samples):")
print(data_matrix)
print("\nCovariance Matrix:")
print(cov_matrix)
print("\nCorrelation Matrix:")
print(corr_matrix)


Data Matrix (features x samples):
[[0.70609599 0.76468826 0.65080148 0.64197221 0.24687491 0.60313184
  0.14772105 0.2816035  0.6546918  0.77983538]
 [0.4681394  0.89686387 0.92174144 0.55051289 0.35988312 0.06742645
  0.31586466 0.7494559  0.15882416 0.72084221]
 [0.77349672 0.80519748 0.08552869 0.82022041 0.7445061  0.39082133
  0.67825939 0.99412851 0.63198614 0.0566796 ]
 [0.84622805 0.7039074  0.28456073 0.29694702 0.64128307 0.90664218
  0.63801828 0.74363295 0.59680448 0.33755725]]

Covariance Matrix:
[[ 0.04813834  0.01695091 -0.02742208 -0.01096554]
 [ 0.01695091  0.0802601  -0.01062965 -0.02813256]
 [-0.02742208 -0.01062965  0.09076678  0.03034749]
 [-0.01096554 -0.02813256  0.03034749  0.0449462 ]]

Correlation Matrix:
[[ 1.          0.27270788 -0.41485034 -0.23574265]
 [ 0.27270788  1.         -0.12453908 -0.46839561]
 [-0.41485034 -0.12453908  1.          0.47513037]
 [-0.23574265 -0.46839561  0.47513037  1.        ]]
